name: LAPRAS Card

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@main
        with:
          SHARE_ID: "yutakobayashi"
          ICON_FIRST: "#03102f"
          ICON_SECOND: "#1688bf"
          BACKGROUND_FIRST: "#020e27"
          BACKGROUND_SECOND: "#0e5593"
          LANG: "en"
          UPDATE_TIME: "false"