name: Update README
on:
  schedule: # Run workflow automatically
    - cron: '30 18 * * *'
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme:
    name: Update Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "4"
          remove_duplicates: true
          feed_list: 'https://zenn.dev/yutakobayashi/feed,https://qiita.com/yutakobayashi/feed'

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
